name: OpenTofu CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tofu:
    name: Tofu Plan and Apply
    runs-on: ubuntu-latest

    # Definimos variables de entorno para autenticarnos con AWS
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} # Requerido por AWS Academy
      AWS_REGION: "us-east-1"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Tofu Init
        run: tofu init

      - name: Tofu Format Check
        run: tofu fmt -check

      - name: Tofu Plan
        run: tofu plan

      - name: Tofu Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: tofu apply -auto-approve